[package]
name = "niimprint-rs"
version = "0.1.0"
edition = "2024"
description = "Rust client library for Niimbot label printers over USB or Bluetooth."
license = "MIT"
readme = "README.md"
repository = "https://github.com/shellixyz/niimprint-rs"
homepage = "https://github.com/shellixyz/niimprint-rs"
keywords = ["niimbot", "printer", "label", "bluetooth", "serial"]
categories = ["command-line-utilities", "hardware-support"]

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
env_logger = "0.11.10"
image = { version = "0.25.10", default-features = false, features = ["png", "jpeg"] }
log = "0.4.29"
serialport = "4.9.0"

[target.'cfg(target_os = "linux")'.dependencies]
bluer = { version = "0.17.4", default-features = false, features = ["bluetoothd"] }
tokio = { version = "1.52.2", features = ["io-util", "rt-multi-thread", "time"] }
tokio-stream = { version = "0.1.19" }
